Filmes and user controllers
vlasabo/java-filmorate pull request #2
Opened 2022-09-08 14:35 UTC by vlasabo

Added films and user controllers, checks and tests

2022-09-09 14:30 UTC, chewmag requested changes
Приветствую Владимир!

Работа полностью покрывает требования задания, все требуемые аспекты ТЗ раскрыты. Предлагаю рассмотреть возможность реализации улучшений, касающихся вынесении всей валидационной логики из контроллеров в отдельные валидаторы, которые будут вызываться спрингом.

2022-09-09 14:30 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +		if (film.getReleaseDate().isBefore(Film.FIRST_FILM_RELEASE_DAY)) {
Лучше реализовать отдельный валидатор для этой даты, например вот так:

```
import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;
import java.time.LocalDate;

public class DateValidator implements ConstraintValidator<ValidFilmDate, LocalDate> {
    static final LocalDate MIN_RELEASE_DATE = LocalDate.of(1895, 12, 28);

    public void initialize(ValidFilmDate constraint) {
    }

    public boolean isValid(LocalDate value, ConstraintValidatorContext context) {
        return !value.isBefore(MIN_RELEASE_DATE);
    }
}
```

2022-09-09 14:30 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +		if (film.getReleaseDate().isAfter(Film.FIRST_FILM_RELEASE_DAY)
Здесь тоже изящнее было бы доверить валидацию отдельному классу.

2022-09-09 14:30 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +		if (user.getLogin().contains(" ")) {
Тоже бы отдельный валидатор )

2022-09-09 14:30 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +
Много пустых строк, ниже все сжато )

2022-09-11 09:54 UTC, vlasabo commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +		if (film.getReleaseDate().isBefore(Film.FIRST_FILM_RELEASE_DAY)) {
Спасибо за пример, сделал как ты сказал - так гораздо больше нравится, вроде вышло более читаемо и удобно. Спасибо

2022-09-11 09:54 UTC, vlasabo commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +		if (film.getReleaseDate().isAfter(Film.FIRST_FILM_RELEASE_DAY)
сделано

2022-09-11 09:55 UTC, vlasabo commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +		if (user.getLogin().contains(" ")) {
Тоже сделано

2022-09-11 09:55 UTC, vlasabo commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +
поправил

2022-09-11 14:35 UTC, chewmag requested changes
Приветствую Владимир!

Спасибо за внедрение улучшений ). В классе src/main/java/ru/yandex/practicum/filmorate/validators/LoginValidator.java не хватает отступов в строке.

2022-09-11 14:35 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/validators/LoginValidator.java
> +        if (value==null){
Что-то отступов в строке не хватает )

2022-09-11 15:23 UTC, vlasabo commented on src/main/java/ru/yandex/practicum/filmorate/validators/LoginValidator.java
> +        if (value==null){
Добавлены два пробела

2022-09-11 17:34 UTC, chewmag approved these changes
Здравствуйте Владимир!

Исправлять больше нечего, можно мерджить PR в main :)

2022-09-12 06:45 UTC, merged