Add database
vlasabo/java-filmorate pull request #4
Opened 2022-10-20 16:01 UTC by vlasabo

Добавлены все методы для работы с БД

2022-10-21 10:39 UTC, sergeymamonov requested changes

2022-10-21 10:39 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        genresId.stream().forEach(genre -> jdbcTemplate.update(SQL_ADD_FILM_GENRES, filmId, genre));
Запросы в цикле к базе не очень хорошая вещь. Желательно делать минимальное количество запросов.

2022-10-21 10:39 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/film_attributes/Genre.java
> +    public Genre(String name, int id) {
Почему бы не воспользоваться аннотацией Lombok?

2022-10-21 10:39 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            user = checkMutuallyAndAddOrRemoveFriend(user, friendId, true);
Строки 39 и 41 одно и тоже название переменной в разных областях видимости. Это не очень хорошо, так как легко перепутать

2022-10-21 13:48 UTC, vlasabo commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        genresId.stream().forEach(genre -> jdbcTemplate.update(SQL_ADD_FILM_GENRES, filmId, genre));
Убрано, запрос теперь формируется одной строкой и отправляется после завершения цикла

2022-10-21 13:49 UTC, vlasabo commented on src/main/java/ru/yandex/practicum/filmorate/model/film_attributes/Genre.java
> +    public Genre(String name, int id) {
Воспользовался @Data, конструктор убрал

2022-10-21 13:49 UTC, vlasabo commented on src/main/resources/schema.sql
> +--INSERT INTO users (id, email,login,name)
убрал

2022-10-21 13:51 UTC, vlasabo commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            user = checkMutuallyAndAddOrRemoveFriend(user, friendId, true);
Убрал переменную внутри if вообще, она в дальнейшем не используется и не нужна

2022-10-22 04:54 UTC, sergeymamonov approved these changes

2022-10-22 04:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        jdbcTemplate.update(query);
Посмотрите jdbcTemplate.batchUpdate
С помощью стрингбилдера собирается строка запросов, но количество запросов к БД как было, так и осталось.

2022-10-22 04:54 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/UserDaoTests.java
> +        User user1 = new User("test@test1.com", "login1", "vladimir1", LocalDate.ofEpochDay(1));
Старайтесь выделять дублирующийся код в отдельный метод/методы.

2022-10-23 05:46 UTC, vlasabo commented on src/test/java/ru/yandex/practicum/filmorate/UserDaoTests.java
> +        User user1 = new User("test@test1.com", "login1", "vladimir1", LocalDate.ofEpochDay(1));
Сделано

2022-10-23 05:46 UTC, vlasabo commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        jdbcTemplate.update(query);
Спасибо, почитал, разобрался, изменил

2022-10-23 05:47 UTC, merged